OPENAI_API_KEY = "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"  # Replace with your OpenAI API key

GCP_CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "your-project-id",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n",
  "client_email": "your-bot@your-project-id.iam.gserviceaccount.com",
  "client_id": "...",
  ...
}
"""
